name: cooking_record
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+8

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^13.0.0
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  image_picker: ^1.0.5
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  uuid: ^4.3.3
  sqflite: ^2.3.2
  path_provider: ^2.1.2
  path: ^1.8.3
  share_plus: ^12.0.1
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.7
  riverpod_generator: ^2.3.9
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.9

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/splash/splash_icon.png
  android: true
  ios: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/bg_image.png
    - assets/splash/splash_icon.png
